WITH RECURSIVE TREE AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT D.ID, D.PARENT_ID, T.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA AS D
    JOIN TREE AS T ON D.PARENT_ID = T.ID
)

SELECT ID FROM TREE
WHERE GENERATION = 3
