WITH 

FIRST AS (SELECT * FROM ECOLI_DATA WHERE PARENT_ID IS NULL),
SECOND AS (SELECT * FROM ECOLI_DATA WHERE PARENT_ID IN (SELECT ID FROM FIRST)),
THIRD AS (SELECT * FROM ECOLI_DATA WHERE PARENT_ID IN (SELECT ID FROM SECOND))

SELECT ID FROM THIRD ORDER BY ID
