WITH SUMMARY AS (
    SELECT *,
        (GENOTYPE & 1) > 0 AS ONE,
        (GENOTYPE & 2) > 0 AS TWO,
        (GENOTYPE & 4) > 0 AS THREE,
        (GENOTYPE & 8) > 0 AS FOUR
    FROM ECOLI_DATA
)

SELECT COUNT(ID) AS COUNT
FROM SUMMARY
WHERE (NOT TWO) AND (ONE OR THREE)