SELECT P.PRODUCT_CODE, P.PRICE * SUM(COALESCE(S.SALES_AMOUNT, 0)) AS SALES
FROM PRODUCT AS P
LEFT OUTER JOIN OFFLINE_SALE AS S 
ON P.PRODUCT_ID = S.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC, P.PRODUCT_CODE ASC
