WITH SALES AS (
    SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT 
    FROM ONLINE_SALE
    UNION
    SELECT SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT 
    FROM OFFLINE_SALE
)

SELECT 
    DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE, 
    PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM SALES
WHERE SALES_DATE LIKE "2022-03%"
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID
