WITH 

NOT_AVAILABLE_CARS AS (
    SELECT DISTINCT CAR_ID 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= "2022-11-30" AND END_DATE >= "2022-11-01"
),

DISCOUNT_PLAN AS (
    SELECT CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
    WHERE DURATION_TYPE = "30일 이상"
),

RESULT AS (
    SELECT DISTINCT C.CAR_ID, C.CAR_TYPE, 
        30 * C.DAILY_FEE * (1 - COALESCE(D.DISCOUNT_RATE, 0) / 100) AS FEE 
    FROM CAR_RENTAL_COMPANY_CAR AS C
    LEFT JOIN NOT_AVAILABLE_CARS AS N ON C.CAR_ID = N.CAR_ID
    LEFT JOIN DISCOUNT_PLAN AS D ON C.CAR_TYPE = D.CAR_TYPE
    WHERE N.CAR_ID IS NULL
)

SELECT CAR_ID, CAR_TYPE, FEE
FROM RESULT
WHERE FEE >= 500000 AND FEE < 2000000
    AND CAR_TYPE IN ("세단", "SUV")
ORDER BY FEE DESC, CAR_TYPE
