WITH SUMMARY AS (
    SELECT ID,
    RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS RN,
    COUNT(ID) OVER() AS N
    FROM ECOLI_DATA
)

SELECT ID, 
    CASE
        WHEN RN * 4 <= N * 1 THEN "CRITICAL"
        WHEN RN * 4 <= N * 2 THEN "HIGH"
        WHEN RN * 4 <= N * 3 THEN "MEDIUM"
        WHEN RN * 4 <= N * 4 THEN "LOW"
        ELSE NULL
    END AS COLONY_NAME
FROM SUMMARY
ORDER BY ID
