WITH 

USERS AS (
    SELECT USER_ID, GENDER
    FROM USER_INFO
),

SALES AS (
    SELECT DISTINCT
        USER_ID, 
        YEAR(SALES_DATE) AS YEAR,
        MONTH(SALES_DATE) AS MONTH
    FROM ONLINE_SALE
),

SUMMARY AS (
    SELECT S.YEAR, S.MONTH, U.GENDER
    FROM SALES AS S
    LEFT JOIN USERS AS U
    ON S.USER_ID = U.USER_ID
)

SELECT *, COUNT(*) AS USERS 
FROM SUMMARY
GROUP BY YEAR, MONTH, GENDER
HAVING GENDER IS NOT NULL
ORDER BY YEAR, MONTH, GENDER
