WITH SUMMARY AS (
    SELECT ROUTE, SUM(D_BETWEEN_DIST) AS TOTAL, COUNT(*) AS COUNT
    FROM SUBWAY_DISTANCE
    GROUP BY ROUTE
)

SELECT ROUTE, 
    CONCAT(ROUND(TOTAL, 1), "km") AS TOTAL_DISTANCE,
    CONCAT(ROUND((TOTAL / COUNT), 2), "km") AS AVERAGE_DISTANCE
FROM SUMMARY
ORDER BY TOTAL DESC
