WITH 

USERS AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = "2021"
),

SALES AS (
    SELECT *, YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH
    FROM ONLINE_SALE
)

SELECT S.YEAR, S.MONTH,
    COUNT(DISTINCT U.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT U.USER_ID) / (SELECT COUNT(*) FROM USERS), 1) AS PURCHASED_RATIO
FROM SALES AS S
JOIN USERS AS U ON S.USER_ID = U.USER_ID
GROUP BY S.YEAR, S.MONTH
ORDER BY YEAR, MONTH
