WITH RECURSIVE TREE AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    
    SELECT D.ID, D.PARENT_ID, T.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA AS D
    JOIN TREE AS T ON D.PARENT_ID = T.ID
)

SELECT COUNT(T.ID) AS COUNT, T.GENERATION
FROM TREE AS T
LEFT JOIN TREE AS CHILD ON T.ID = CHILD.PARENT_ID
WHERE CHILD.ID IS NULL
GROUP BY T.GENERATION
ORDER BY T.GENERATION
