WITH SUMMARY AS (
    SELECT CAR_ID, "2022-10-16" BETWEEN START_DATE AND END_DATE AS RENT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
)

SELECT CAR_ID, 
    CASE
        WHEN MAX(RENT)
        THEN "대여중"
        ELSE "대여 가능"
    END AS AVAILABILITY
FROM SUMMARY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC
