WITH HISTORY AS (
    SELECT *, DATEDIFF(END_DATE, START_DATE) + 1 AS DIFF,
    CASE 
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN "90일 이상"
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN "30일 이상"
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN "7일 이상"
        ELSE "7일 미만"
    END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
)

SELECT H.HISTORY_ID,
    C.DAILY_FEE * H.DIFF * (1 - COALESCE(P.DISCOUNT_RATE, 0) / 100.0) AS FEE
FROM HISTORY AS H
LEFT JOIN CAR_RENTAL_COMPANY_CAR AS C
ON H.CAR_ID = C.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P 
ON C.CAR_TYPE = P.CAR_TYPE AND H.DURATION_TYPE = P.DURATION_TYPE
WHERE C.CAR_TYPE = "트럭"
ORDER BY FEE DESC, H.HISTORY_ID DESC
