WITH SUMMARY AS (
    SELECT F.FLAVOR, F.TOTAL_ORDER + COALESCE(J.TOTAL_ORDER, 0) AS TOTAL_ORDER
    FROM FIRST_HALF AS F
    LEFT JOIN JULY AS J ON F.SHIPMENT_ID = J.SHIPMENT_ID

    UNION

    SELECT J.FLAVOR, J.TOTAL_ORDER + COALESCE(F.TOTAL_ORDER, 0) AS TOTAL_ORDER
    FROM FIRST_HALF AS F
    RIGHT JOIN JULY AS J ON F.SHIPMENT_ID = J.SHIPMENT_ID    
),
RESULT AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
    FROM SUMMARY
    GROUP BY FLAVOR
)

SELECT FLAVOR
FROM RESULT
ORDER BY TOTAL DESC
LIMIT 3
