WITH RECURSIVE 

ANIMALS AS (
    SELECT ANIMAL_ID, HOUR(DATETIME) AS HOUR
    FROM ANIMAL_OUTS
),

HOURS AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM HOURS
    WHERE HOUR + 1 < 24
)

SELECT H.HOUR, COUNT(ANIMAL_ID) AS COUNT 
FROM ANIMALS AS A 
RIGHT JOIN HOURS AS H USING (HOUR)
GROUP BY H.HOUR
ORDER BY H.HOUR
