WITH FRONTEND AS (
    SELECT *
    FROM SKILLCODES
    WHERE CATEGORY LIKE "Front%"
)

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE SKILL_CODE & (SELECT SUM(CODE) FROM FRONTEND)
ORDER BY ID
