WITH SUMMARY AS (
    SELECT WRITER_ID AS USER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = "DONE"
    GROUP BY WRITER_ID
)

SELECT U.USER_ID, U.NICKNAME, S.TOTAL_SALES
FROM SUMMARY AS S
JOIN USED_GOODS_USER AS U
ON S.USER_ID = U.USER_ID
WHERE TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES
