WITH GRADE AS (
    SELECT EMP_NO, 
    CASE
        WHEN SUM(SCORE) >= 96 * 2 THEN "S"
        WHEN SUM(SCORE) >= 90 * 2 THEN "A"
        WHEN SUM(SCORE) >= 80 * 2 THEN "B"
        ELSE "C"
    END AS GRADE
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
)

SELECT E.EMP_NO, E.EMP_NAME, G.GRADE,
    CASE
        WHEN GRADE = "S" THEN ROUND(SAL * 0.20)
        WHEN GRADE = "A" THEN ROUND(SAL * 0.15)
        WHEN GRADE = "B" THEN ROUND(SAL * 0.10)
        ELSE 0
    END AS BONUS
FROM HR_EMPLOYEES AS E
JOIN GRADE AS G
ON E.EMP_NO = G.EMP_NO
ORDER BY EMP_NO
