WITH 

HISTORY AS (
    SELECT * 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN "2022-08-01" AND "2022-10-31"
),

SUMMARY AS (
    SELECT CAR_ID, COUNT(CAR_ID) AS COUNT
    FROM HISTORY
    GROUP BY CAR_ID
),

RESULT AS (
    SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(CAR_ID) AS RECORDS
    FROM HISTORY
    WHERE CAR_ID IN (SELECT CAR_ID FROM SUMMARY WHERE COUNT >= 5)
    GROUP BY MONTH(START_DATE), CAR_ID
)

SELECT MONTH, CAR_ID, RECORDS
FROM RESULT
WHERE RECORDS > 0
ORDER BY MONTH ASC, CAR_ID DESC
