SELECT FI.ID, NI.FISH_NAME, FI.LENGTH
FROM FISH_INFO AS FI
JOIN FISH_NAME_INFO AS NI ON FI.FISH_TYPE = NI.FISH_TYPE
WHERE (FI.FISH_TYPE, FI.LENGTH) 
IN (SELECT FISH_TYPE, MAX(LENGTH) FROM FISH_INFO GROUP BY FISH_TYPE);
