# 022년도 평가 점수가 가장 높은 사원들의 점수, 사번, 성명, 직책, 이메일

SELECT SUM(G.SCORE) AS SCORE, 
    E.EMP_NO AS EMP_NO, E.EMP_NAME AS EMP_NAME, 
    E.POSITION AS POSITION, E.EMAIL AS EMAIL
FROM HR_EMPLOYEES AS E
LEFT JOIN HR_GRADE AS G ON E.EMP_NO = G.EMP_NO
WHERE G.YEAR = 2022
GROUP BY EMP_NO
ORDER BY SCORE DESC
LIMIT 1