WITH SUMMARY AS (
    SELECT D.DEPT_ID, D.DEPT_NAME_EN, 
    ROUND(AVG (E.SAL)) AS AVG_SAL
    FROM HR_EMPLOYEES AS E
    LEFT JOIN HR_DEPARTMENT AS D
    ON E.DEPT_ID = D.DEPT_ID
    GROUP BY DEPT_ID
)

SELECT * FROM SUMMARY
ORDER BY AVG_SAL DESC
