WITH MAX_ITEMS AS (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT AS PRODUCT
    GROUP BY CATEGORY
)

SELECT P.CATEGORY, P.PRICE AS MAX_PRICE, P.PRODUCT_NAME
FROM FOOD_PRODUCT AS P
LEFT JOIN MAX_ITEMS AS M ON P.CATEGORY = M.CATEGORY
WHERE P.CATEGORY IN ("과자", "국", "김치", "식용유") AND P.PRICE = M.MAX_PRICE
ORDER BY P.PRICE DESC
