WITH FISH AS (
    SELECT ID, FISH_TYPE, COALESCE(LENGTH, 10) AS LENGTH
    FROM FISH_INFO
)

SELECT COUNT(ID) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE 
FROM FISH
GROUP BY FISH_TYPE 
HAVING SUM(LENGTH) >= 33 * COUNT(ID)
ORDER BY FISH_TYPE;
