WITH

FRONTEND AS (
    SELECT SUM(CODE) AS CODE 
    FROM SKILLCODES 
    WHERE CATEGORY LIKE "Front%"
),

PYTHON AS (
    SELECT CODE 
    FROM SKILLCODES 
    WHERE NAME LIKE "Python"
),

CSHARP AS (
    SELECT CODE 
    FROM SKILLCODES 
    WHERE NAME LIKE "C#"
),

SUMMARY AS (
    SELECT *,
    CASE 
        WHEN SKILL_CODE & (SELECT CODE FROM FRONTEND) 
            AND SKILL_CODE & (SELECT CODE FROM PYTHON) THEN "A"
        WHEN SKILL_CODE & (SELECT CODE FROM CSHARP) THEN "B"
        WHEN SKILL_CODE & (SELECT CODE FROM FRONTEND) THEN "C"
        ELSE NULL
    END AS GRADE
    FROM DEVELOPERS
)

SELECT GRADE, ID, EMAIL
FROM SUMMARY
WHERE GRADE IS NOT NULL
ORDER BY GRADE, ID
